"use client";

import { motion } from "framer-motion";
import { UserCircle, Award, Shield, Sunrise } from "lucide-react";

const commitments = [
  {
    icon: <UserCircle className="w-7 h-7" />,
    title: "Customer First",
    desc: "Every service is planned around your system's specific needs.",
    color: "from-blue-500 to-primary-600"
  },
  {
    icon: <Award className="w-7 h-7" />,
    title: "Quality Without Compromise",
    desc: "We never rush jobs or take shortcuts.",
    color: "from-cyan-500 to-teal-500"
  },
  {
    icon: <Shield className="w-7 h-7" />,
    title: "Safety at Every Step",
    desc: "Trained technicians and safe cleaning procedures.",
    color: "from-rose-500 to-pink-500"
  },
  {
    icon: <Sunrise className="w-7 h-7" />,
    title: "Long-Term Solar Performance",
    desc: "Helping customers protect their investment for years to come.",
    color: "from-amber-500 to-orange-500"
  },
];

export default function AboutPage() {
  return (
    <div className="pt-20">
      {/* Hero */}
      <section className="py-12 md:py-16 bg-hero-gradient">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto text-center">
            <motion.div initial={false}>
              <span className="inline-block px-4 py-1.5 rounded-full bg-primary-50 text-primary-600 text-[13px] font-bold tracking-widest uppercase mb-6 border border-primary-100 shadow-sm">
                About Us
              </span>
              <h1 className="text-3xl md:text-5xl lg:text-6xl font-black text-primary-900 mb-8 leading-[1.15] tracking-tight">
                Maximizing <span className="gradient-text">Solar Performance</span><br className="hidden md:block" /> Across Ahmedabad
              </h1>
              <div className="text-lg sm:text-xl text-gray-600 leading-relaxed font-medium max-w-3xl mx-auto space-y-4">
                <p>
                  Yavix Solar Cleaning was founded with a clear purpose — to help homeowners, businesses and industries maximize the power generated by their solar panels.
                </p>
                <p>
                  We believe that professional cleaning is one of the simplest yet most impactful ways to improve efficiency, increase energy output and protect long-term system performance.
                </p>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Story */}
      <section className="py-12 md:py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
            <motion.div initial={{ opacity: 0, x: -24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.7 }}>
              <span className="inline-block px-4 py-1.5 rounded-full bg-primary-50 text-primary-600 text-[12px] font-bold tracking-widest uppercase mb-5 border border-primary-100">
                Our Story
              </span>
              <h2 className="text-2xl md:text-4xl font-black text-primary-900 mb-8 leading-tight tracking-tight">
                From a Local Challenge to a <br className="hidden lg:block" />City-Wide Solution
              </h2>
              <div className="space-y-6 text-[16px] sm:text-[17px] text-gray-600 leading-relaxed font-medium">
                <p>
                  As solar installations expanded across the country, one challenge became increasingly common: <strong className="text-primary-800">dirty solar panels reducing energy production.</strong> Dust, pollution, bird droppings and mineral deposits can significantly impact system performance if left untreated.
                </p>
                <p>
                  In Gujarat, the combination of a dry, dusty climate and hard water conditions causes solar panels to accumulate contaminants quickly. These deposits can block sunlight, reduce energy output and affect long-term system efficiency if not properly removed. Without regular professional cleaning, solar panels can lose up to <strong className="text-red-600">20–35% of their performance</strong> over time.
                </p>
                <p>
                  Yavix Solar Cleaning was established to solve this challenge through professional solar panel cleaning services.
                </p>
              </div>
            </motion.div>

            <motion.div initial={{ opacity: 0, x: 24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.7 }}
              className="grid grid-cols-2 gap-4 sm:gap-6">
              {[
                { val: "5000+", label: "Solar Panels Cleaned" },
                { val: "200+", label: "Satisfied Clients" },
                { val: "50+", label: "Commercial Projects" },
                { val: "5+", label: "Star Rated Service" },
              ].map((s) => (
                <div key={s.label} className="p-4 sm:p-8 rounded-3xl bg-white border border-gray-100 shadow-[0_8px_30px_rgb(0,0,0,0.04)] text-center flex flex-col justify-center hover:-translate-y-1 transition-transform duration-300">
                  <p className="text-3xl md:text-5xl font-black text-primary-600 mb-2">{s.val}</p>
                  <p className="text-[12px] sm:text-[15px] text-gray-500 font-semibold">{s.label}</p>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* Commitments */}
      <section className="py-12 md:py-16 bg-[#f8fafc]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.7 }} className="text-center mb-12">
            <span className="inline-block px-4 py-1.5 rounded-full bg-primary-50 text-primary-600 text-[12px] font-bold tracking-widest uppercase mb-5 border border-primary-100">
              Our Commitment
            </span>
            <h2 className="text-3xl md:text-5xl font-black text-primary-900 tracking-tight">What Drives Us</h2>
          </motion.div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {commitments.map((v, i) => (
              <motion.div key={v.title} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6, delay: i * 0.1 }}
                whileHover={{ y: -8, boxShadow: "0 25px 50px -12px rgba(0, 102, 255, 0.2)" }}
                className="p-8 rounded-3xl bg-white border border-gray-100 shadow-sm transition-all duration-300 flex flex-col h-full hover:border-primary-200 group">
                <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${v.color} flex items-center justify-center text-white shadow-lg shadow-blue-500/20 mb-6`}>
                  {v.icon}
                </div>
                <h3 className="font-black text-[20px] text-primary-900 leading-snug mb-3 group-hover:text-primary-600 transition-colors">{v.title}</h3>
                <p className="text-[15px] text-gray-500 leading-relaxed font-medium">{v.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
